// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Paintball.Database.Contexts;

#nullable disable

namespace Paintball.Database.Migrations
{
    using System.Diagnostics.CodeAnalysis;

    
    [DbContext(typeof(GameResultContext))]
    partial class GameResultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Paintball.Database.Abstractions.Entities.GameResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamOne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamOneMatchPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamTwo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamTwoMatchPoints")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameResults");
                });
#pragma warning restore 612, 618
        }
    }
}
